# Generated by Django 2.0.3 on 2018-03-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('discribe', models.TextField()),
                ('start', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=33)),
                ('name', models.CharField(max_length=64)),
                ('reply_token', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=64)),
                ('hwid', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('zipcode', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('hwid', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeyan.Place')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeyan.User'),
        ),
    ]
