# Generated by Django 2.0.2 on 2018-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_beacon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beacon',
            old_name='user_id',
            new_name='line_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_url',
            new_name='url',
        ),
    ]
