# Generated by Django 2.0.2 on 2018-03-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_auto_20180309_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beacon',
            new_name='LineUser',
        ),
    ]
