# Generated by Django 2.0.2 on 2018-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0004_auto_20180309_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='reply_token',
            field=models.CharField(default=2, max_length=512),
        ),
    ]
