# Generated by Django 2.0.2 on 2018-03-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('event_url', models.CharField(max_length=1024)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1024)),
                ('line_id', models.CharField(max_length=1024)),
                ('timestamp', models.CharField(max_length=1024)),
                ('hw_id', models.CharField(max_length=1024)),
                ('reply_token', models.CharField(max_length=1024)),
                ('freeday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1024)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1024)),
                ('user_id', models.CharField(max_length=64)),
                ('eeyan', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=32)),
                ('beacon_id', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
    ]
