# Generated by Django 2.0.2 on 2018-03-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_lineuser_eeyan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss.Event'),
        ),
    ]
